baseURL = "https://pierini.tk/"
languageCode = "en-us"
title = "Pierini web site"

baseurl = "/"

theme = "hermit"

name = "Hermit"
license = "MIT"
licenselink = "https://github.com/Track3/hermit/blob/master/LICENSE"
description = "Pier Alberto Pierini`s web site"
homepage = "https://github.com/Track3/hermit"
tags = ["blog", "minimal", "dark", "responsive"]
features = [
  "single column",
  "featured image",
  "social icons",
  "google analytics",
  "disqus"
]
min_version = 0.43

[author]
  name = "Track3"
  homepage = "https://www.xxxlbox.com"
