baseURL = "https://pierini.tk"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Pierini web site"

baseurl = "/"
#copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
theme = "hermit"
enableEmoji = true
#name = "Hermit"
#license = "MIT"
#licenselink = "https://github.com/Track3/hermit/blob/master/LICENSE"
#description = "Pier Alberto Pierini`s web site"
#homepage = "https://github.com/Track3/hermit"
#tags = ["minimal", "dark", "responsive"]

features = [
  "single column",
  "featured image",
  "social icons",
  "google analytics",
  "disqus"
]
min_version = 0.43

homeSubtitle = "My personal Portfolio"

[taxonomies]
tag = "tags"

[author]
  name = "Pier Alberto"
  homepage = "https://www.pierini.com"


[menu]

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 40

  [[menu.main]]
    name = "Contact Me"
    url = "contactme/"
    weight = 30

    [[menu.main]]
    name = "Data Center ZERO"
    url = "datacenterzero/"
    weight = 20
  
    [[menu.main]]
    name = "Pier Alberto"
    url = "pieralberto/"
    weight = 10
  
    [[menu.main]]
    name = "Services"
    url = "services/"
    weight = 30

  [[params.social]]
    name = "github"
    url = "https://github.com/pieralbertopierini"