baseURL = ""
languageCode = "en-us"
title = "Pierini web site"

baseurl = "/"

theme = "hermit"

name = "Hermit"
license = "MIT"
licenselink = "https://github.com/Track3/hermit/blob/master/LICENSE"
description = "Pier Alberto Pierini`s web site"
homepage = "https://github.com/Track3/hermit"
tags = ["blog", "minimal", "dark", "responsive"]
features = [
  "single column",
  "featured image",
  "social icons",
  "google analytics",
  "disqus"
]
min_version = 0.43

[author]
  name = "Track3"
  homepage = "https://www.xxxlbox.com"


[menu]

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 10

  [[menu.main]]
    name = "Contact Me"
    url = "contactme/"
    weight = 20

    [[menu.main]]
    name = "Data Center ZERO"
    url = "datacenterzero/"
    weight = 30
  
    [[menu.main]]
    name = "Pier Alberto"
    url = "pieralberto/"
    weight = 40
  
    [[menu.main]]
    name = "Services"
    url = "services/"
    weight = 20